# 딥러닝 프레임워크(Deep Learning Framework)

## 1. 딥러닝 프레임워크 개요

### 1-1 다음 빈 칸에 들어갈 알맞은 말을 써넣어주세요. <br>
- (a)(이)란 여러 층을 가진 인공신경망을 사용하여(Artificial Neural Network)을 사용하여 머신러닝 학습을 수행하는 것으로 심층학습이라고도 불린다.
- (b)(이)란 응용 프로그램을 개발하기 위한 여러 라이브러리나 모듈 등을 효율적으로 사용할 수 있도록 하나로 묶어 놓은 일종의 패키지이다.

정답 (a) : 딥러닝   , (b) : 프레임워크

### 1-2 다음 빈 칸에 공통으로 들어갈 알맞은 말을 써넣어주세요. <br>
- (    )(이)란 딥러닝 모델을 쉽게 구현하고 학습할 수 있도록 도와주는 도구이다.
- (    )(이)(는) 라이브러리, 프레임워크, 툴킷 등과 같은 용어로 불리며, 머신러닝 기술을 사용해 필요한 기능을 빠르게 제공하고 편리한 인터페이스를 제공한다.
- (    )은(는) 대부분 오픈소스로 제공되며, 다양한 언어로 자유롭게 사용할 수 있다.

정답 : 딥러닝 프레임워크

## 2. 딥러닝 프레임워크 종류

### 2-1 다음 보기 중 각 딥러닝 프레임워크에 알맞는 특징을 골라주세요.(각 2개씩) <br>
#### (a) Google이 개발한 오픈소스 딥러닝 프레임워크입니다.
#### (b) Meta(Facebook)이 개발한 오픈소스 딥러닝 프레임워크입니다.
#### (c) TensorFlow, Theano, CNTK와 같은 백엔드 엔진과 함께 사용할 수 있습니다.
#### (d) 어렵고 복잡하다는 TensorFlow의 문제를 해결하기 위해 개발되었습니다.
#### (e) 데이터 플로우 그래프(Data Flow Graph)구조를 사용하는 특징이 있습니다.
#### (f) 앞으로 비타민 딥러닝 세션에 계속 사용될 딥러닝 프레임워크입니다.

#### 1.텐서플로우 : (a), (e) 
#### 2. 케라스 : (c), (d)
#### 3. 파이토치 : (b), (f)

### 2-2 2017년 기준 텐서플로우, 케라스, 파이토치를 점유율 순위대로 나열하시오.

정답 :텐서플로우,케라스 ,파이토치 

### 2-3 2023년 기준 텐서플로우, 케라스, 파이토치를 점유율 순위대로 나열하시오.

정답 : 파이토치, 텐서플로우 , 케라스

## 3. 텐서플로우

### 3-1 다음 보기 중 텐서플로우의 장점이 아닌 것을 고르시오. <br>
- (1) 구글에서 전폭적으로 지원하고 있기 때문에 지속적인 성능 개선과 지원에서 강점을 보인다.
- (2) 추상화 수준이 높아 개발자가 알고리즘의 세세한 구현보다 전체적인 논리 자체에 더 집중할 수 있게 된다.
- (3) 초보자와 전문가 모두 이해하기 쉬운 고수준 API를 제공하며, 다양한 백엔드 엔진을 지원한다.
- (4) 대형 신경망 작업을 처리할 수 있는 높은 성능을 가지고 있다.

정답 : (3)

### 3-2 다음 보기 중 텐서플로우의 단점이 아닌 것을 고르시오. <br>
- (1) 타 프레임워크에 비해 메모리를 효율적으로 사용하지 못한다.
- (2) 타 프레임워크에 비해 속도가 느린 편이다.
- (3) 딥러닝 모델을 만드는 데 기초 레벨부터 직접 작업해야 하기 때문에 초보자가 사용하기 어려울 수 있다.
- (4) 파이토치와 비교하여 후발주자이기 때문에 점유율이 낮다.

정답 : (4) 

## 4. 케라스

### 4-1 다음 보기 중 케라스의 장점이 아닌 것을 고르시오. <br>
- (1) 일반 사용 사례에 최적화된 간단하고 일관된 인터페이스를 제공한다.
- (2) 그래프를 만들면서 동시에 값을 할당하는 Define by run 방식으로 코드를 깔끔하고 직관적으로 작성할 수 있다.
- (3) 케라스의 구성 요소는 모듈 형태로, 새로운 모델을 만들 때 각 모듈을 조합해 쉽게 새로운 모델을 만들 수 있다.
- (4) 딥러닝 초급자도 각자 분야에서 손쉽게 딥러닝 모델을 개발하고 활용할 수 있도록 직관적인 API를 제공한다.

정답 : (2)

### 4-2 다음 보기 중 케라스의 단점이 아닌 것을 고르시오. <br>
- (1) 각 모듈이 종속적이기 때문에 관리가 어렵다.
- (2) 모듈화의 한계로 복잡한 프로젝트의 구현 범위가 다소 좁은 편이다.
- (3) 다양한 백엔드 위에서 동작하기 때문에 어떤 오류가 발생했을 때 케라스 자체의 문제인지, 백엔드 언어의 문제인지 특정하기 어렵다.
- (4) 현재 텐서플로우, 케라스, 파이토치 중 점유율이 가장 낮다.

정답 : (1)

## 5. 파이토치

### 5-1 다음 보기 중 파이토치의 장점이 아닌 것을 고르시오. <br>
- (1) Numpy를 대체하면서도 GPU를 이용한 연산이 가능하며 유연하고 빠르다.
- (2) 절차가 간단하고 그래프가 동적으로 변화할 수 있으며 코드 자체도 파이썬과 유사해 진입 장벽이 낮은 편이다.
- (3) 데이터 플로우 그래프를 통해 딥러닝 네트워크 표현이 직관적이다.
- (4) 메모리에서 연산을 하면서도 신경망 사이즈를 최적으로 바꾸면서 동작시킬 수 있어 효율적이다.

정답 : (3)

------

## 6. 파이토치

In [1]:
import torch

6-1 <br>
Output: <br>
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)  <br>
가 나오도록 빈칸을 채워주세요

In [2]:
torch.tensor([[1.,2.],[3.,4.]],dtype=torch.float64)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

6-2  아래의 코드를 실행 후 tensor 와 Tensor가 어떤 점이 다른지 써주세요

In [3]:
tensor = torch.tensor([[1,2],[3,4]])
Tensor = torch.Tensor([[1,2],[3,4]])
print(tensor)
print(Tensor)

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]])


(a) tensor는 리스트 안의 .은 제외하고 숫자만 인식한 반면 Tensor는 .까지 인식하고 있다.

In [4]:
print(torch.tensor(3))
print(torch.Tensor(3))

tensor(3)
tensor([0., 0., 0.])


(b) 입력받은 데이터를 복사해 사용하고, 입력받은 데이터를 메모리 공간으로 사용하는 차이가 있다. 

In [8]:
print(torch.tensor([2.,3.], requires_grad=True))
#print(torch.Tensor([2.,3.], requires_grad=True)) // 오류 발생
print(torch.Tensor([2.,3.]).requires_grad_(True))

tensor([2., 3.], requires_grad=True)
tensor([2., 3.], requires_grad=True)


(c) Tensor에서는 require_grad에 대한 매개변수가 존재하지 않는 듯 하다.

In [6]:
# print(torch.tensor()) // 오류 발생
print(torch.Tensor())

tensor([])


(d) tensor는 값을 입력하지 않으면 오류가 발생한다.

6-3 차원이 다른 텐서들을 연산하기 위해서 차원을 바꾸려고 합니다. 아래의 코드를 채워주세요.

In [15]:
v = torch.tensor([[1,2,3],[3,4,5]])
w = torch.tensor([[1,2],[2,3],[4,5]])

w1=w.view(2,3)
w2=w.permute(1,0)

print(torch.add(v,w1))
print(torch.sub(v,w2))


tensor([[ 2,  4,  5],
        [ 6,  8, 10]])
tensor([[ 0,  0, -1],
        [ 1,  1,  0]])


6-4 squeeze함수는 차원을 줄이는 , unsqueeze 함수는 차원을 늘리는 함수입니다. 아래의 코드를 채워주세요.

In [16]:
x = torch.rand(1,7,46,46)
x = x.squeeze()
print("1인차원 없애기 :", x.shape)


x2 = torch.rand(7,46,46)
x2 = x2.unsqueeze(dim=1)
print("2번쨰 차원에 크기가 1인 차원 추가 :", x2.shape)

1인차원 없애기 : torch.Size([7, 46, 46])
2번쨰 차원에 크기가 1인 차원 추가 : torch.Size([7, 1, 46, 46])


## 7. 클래스

7-1 첫번째 계산기로는 3+7을 하고 싶고, 두번째 계산기로는 3+10을 하고 싶어서 , 두 개의 계산기를 구현하고 싶어서, 두 개의 함수를 독립적으로 구현하였습니다. 이런 두개의 덧셈기를 클래스로 만드는 코드를 채워주세요.

In [9]:
result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


In [11]:
class Calculator:
    def __init__(self):
        self.result=0

    def add(self, num):
        self.result+=num
        return self.result



cal1 = Calculator()
cal2 = Calculator()


print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10


7-2  로지스틱 회귀를 클래스로 구현해보고 이를 학습 평가해보겠습니다.

In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [18]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

7-2-1 파이토치의 nn.Linear와 nn.Sigmoid로 로지스틱 회귀 구현하기위해서 아래의 코드를 채워주세요. <br>선형 레이어는 입력 특성의 차원이 2이고 출력 차원이 1입니다.

In [21]:
model = nn.Sequential(
   nn.Linear(2,1),
   nn.Sigmoid()
)

7-2-2 위에서 구현한 코드를 토대로 로지스틱 회귀 모델은 클래스로 구현해주세요.
<br>클래스 형태의 모델은 nn.Module을 상속받습니다.<br>그리고  __init__() 에서 모델에서 사용될 모듈 , 활성화 함수 등을 정의합니다. foward()에서는 모델에서 실행되어야하는 연산을 정의합니다.

In [22]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(2,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.linear(x))

In [23]:
model = BinaryClassifier()

7-3 학습을 통해 모델의 파라미터를 최적화하고, 정확도를 출력하여 모델의 성능을 평가해보도록 하겠습니다. <br> 다음의 조건에 맞게 코드를 채워주세요.
<br>
(a)
<br>
에폭은 500 으로 설정해주세요.
<br>
(b)
<br>
이진교차엔트로피를 사용하여 예측값과 y_train 간의 손실을 계산해주세요.
<br>
(c)
<br>
옵티마이저의 gradinet를 초기화하고
<br>
손실함수의 gradient 를 계산(역전파 학습)한뒤에
<br>
모델의 파라미터를 업데이트하도록 구현해주세요.

In [24]:
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs =500
for epoch in range(nb_epochs + 1):


    hypothesis = model(x_train)


    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/500 Cost: 1.141724 Accuracy 50.00%
Epoch   10/500 Cost: 0.647589 Accuracy 83.33%
Epoch   20/500 Cost: 0.618605 Accuracy 83.33%
Epoch   30/500 Cost: 0.521262 Accuracy 83.33%
Epoch   40/500 Cost: 0.434128 Accuracy 83.33%
Epoch   50/500 Cost: 0.350855 Accuracy 83.33%
Epoch   60/500 Cost: 0.273270 Accuracy 83.33%
Epoch   70/500 Cost: 0.208481 Accuracy 83.33%
Epoch   80/500 Cost: 0.167539 Accuracy 100.00%
Epoch   90/500 Cost: 0.149163 Accuracy 100.00%
Epoch  100/500 Cost: 0.138407 Accuracy 100.00%
Epoch  110/500 Cost: 0.129377 Accuracy 100.00%
Epoch  120/500 Cost: 0.121475 Accuracy 100.00%
Epoch  130/500 Cost: 0.114501 Accuracy 100.00%
Epoch  140/500 Cost: 0.108299 Accuracy 100.00%
Epoch  150/500 Cost: 0.102748 Accuracy 100.00%
Epoch  160/500 Cost: 0.097751 Accuracy 100.00%
Epoch  170/500 Cost: 0.093229 Accuracy 100.00%
Epoch  180/500 Cost: 0.089116 Accuracy 100.00%
Epoch  190/500 Cost: 0.085360 Accuracy 100.00%
Epoch  200/500 Cost: 0.081915 Accuracy 100.00%
Epoch  210/500 Cost: 