# 1. Numpy 활용 (25점)

넘파이 설치 및 import

In [1]:
# pip install numpy
!pip install numpy # For Google Colab

ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# Numpy의 경우 보통 np라는 명칭으로 임포트합니다.
import numpy as np

1.1 크기 10의 0행렬 생성 후 5번 인덱스로 1을 할당해주세요. (4점)

In [3]:
A = np.zeros(10)
A[5] = 1

print(A)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


1.2 10부터 50 미만의, 간격이 3인 행렬 생성 후 반전해주세요. (6점)

In [4]:
A = np.arange(10, 50, 3)
A = A[::-1]

print(A)

[49 46 43 40 37 34 31 28 25 22 19 16 13 10]


1.3 0~8 범위의 값으로 3x3인 행렬을 생성해주세요. (4점)

In [5]:
A = np.arange(9).reshape(3,3)

print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


1.4 랜덤한 2x3 행렬을 생성해주세요. (4점)

In [6]:
seed = 100
np.random.seed(seed)
A = np.random.rand(2,3)

print(A)

[[0.54340494 0.27836939 0.42451759]
 [0.84477613 0.00471886 0.12156912]]


1.5 0부터 11까지의 값이 들어간 3x4, 0부터 19까지의 값이 순서대로 4x5 행렬을 생성하고 행렬곱을 계산해주세요. (4점)

In [7]:
A = np.arange(0,12).reshape(3,4)
B = np.arange(0,20).reshape(4,5)

print(A.dot(B))

[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]]


1.6 3x3으로 행렬을 생성하고, 행렬의 전치 행렬을 생성해주세요. (3점)

In [8]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A = A.T

print(A)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 2. Pandas 활용 (25점)

판다스 설치 및 import

In [9]:
# pip install pandas
!pip install pandas # For Google Colab

ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
# Pandas의 경우 보통 pd라는 명칭으로 임포트합니다.
import pandas as pd

1. 데이터셋 csv파일을 읽고 하위 3개의 데이터를 출력해주세요.

1점

In [11]:
df = pd.read_csv("./titanic.csv")
df.tail(3)

PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

2. Pclass가 2이고 Fare이 20 이상인 경우를 보여주세요.

2점



In [17]:
df[(df['Pclass']==2) & (df['Fare']>=20)]

PassengerId  Survived  Pclass  \
9             10         1       2   
20            21         0       2   
41            42         0       2   
43            44         1       2   
53            54         1       2   
..           ...       ...     ...   
827          828         1       2   
848          849         0       2   
854          855         0       2   
874          875         1       2   
880          881         1       2   

                                                  Name     Sex   Age  SibSp  \
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
20                                Fynney, Mr. Joseph J    male  35.0      0   
41   Turpin, Mrs. William John Robert (Dorothy Ann ...  female  27.0      1   
43            Laroche, Miss. Simonne Marie Anne Andree  female   3.0      1   
53   Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.0      1   
..                                                 ...     ...   ...    ...   
827                              Mallet, Master. Andre    male   1.0      0   
848                                  Harper, Rev. John    male  28.0      0   
854      Carter, Mrs. Ernest Courtenay (Lilian Hughes)  female  44.0      1   
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   

     Parch           Ticket     Fare Cabin Embarked  
9        0           237736  30.0708   NaN        C  
20       0           239865  26.0000   NaN        S  
41       0            11668  21.0000   NaN        S  
43       2    SC/Paris 2123  41.5792   NaN        C  
53       0             2926  26.0000   NaN        S  
..     ...              ...      ...   ...      ...  
827      2  S.C./PARIS 2079  37.0042   NaN        C  
848      1           248727  33.0000   NaN        S  
854      0           244252  26.0000   NaN        S  
874      0        P/PP 3381  24.0000   NaN        C  
880      1           230433  26.0000   NaN        S  

[80 rows x 12 columns]

3. 파일을 읽고 생성한 데이터프레임을 생존여부 column을 대상으로 하여 groupby를 적용한 df_groupby 변수를 생성해주세요.

3점

In [18]:
df_groupby = df.groupby('Survived')

4. df_groupby 데이터프레임과 aggregation 함수를 활용해 생존한 승객들의 인원수를 알아내보세요.

3점

In [20]:
df_groupby['Survived'].agg('count')

Survived
0    549
1    342
Name: Survived, dtype: int64

5. 생존여부(Survived)와 자리 등급(Pclass)을 대상으로 groupby를 진행한 df_groupby 데이터프레임을 새로 생성하세요. 그리고 PassengerId column만 agg()를 수행해 생존한 2등급석 승객 중 가장 작은 PassengerId를 알아내보세요.

4점

In [23]:
df_groupby = df.groupby(['Survived','Pclass'])
df_groupby.get_group((1, 2))['PassengerId'].min()

10

6. 데이터프레임 df에 생존 여부를 한글로 작성한 column을 추가하고 'Survived' column과 '생존 여부' column을 출력하세요. (apply lambda 활용).

4점

In [24]:
df['생존 여부'] = df['Survived'].apply(lambda x: '생존' if x == 1 else '사망')
print(df[['Survived', '생존 여부']])

     Survived 생존 여부
0           0    사망
1           1    생존
2           1    생존
3           1    생존
4           0    사망
..        ...   ...
886         0    사망
887         1    생존
888         0    사망
889         1    생존
890         0    사망

[891 rows x 2 columns]


7. Age 컬럼을 활용해서 '나이대' 컬럼을 새롭게 만들고 데이터의 수를 출력해주세요.(ex. 23 -> 20대)

(Age 컬럼의 결측치는 자유롭게 처리해주세요)

4점

In [ ]:
df['Age'].'''YOUR CODE'''

df['나이대'] = df.'''YOUR CODE'''

df['나이대'].???()

8. df 내의 컬럼을 활용하여 자유롭게 새로운 컬럼을 생성하고 생성한 컬럼을 구체적으로 설명해주세요.

4점

In [ ]:
df[???] = '''YOUR CODE'''

---

# 3. Sciket-learn (20점)

### [문제 1.1] KNNImputer (2점)

이웃과의 거리가 2가 되도록 코드의 빈칸을 채워주세요.

In [25]:
from sklearn.impute import KNNImputer
import numpy as np

# 예제 데이터 생성
data = np.array([
    [1, 2, np.nan],
    [3, 4, 3],
    [np.nan, 6, 5],
    [8, 8, 7]
])

# KNNImputer 인스턴스 생성
imputer = KNNImputer(n_neighbors=2)

# 결측치 대체 적용
imputed_data = imputer.fit_transform(data)

print("Original Data:\n", data)
print("Imputed Data:\n", imputed_data)

Original Data:
 [[ 1.  2. nan]
 [ 3.  4.  3.]
 [nan  6.  5.]
 [ 8.  8.  7.]]
Imputed Data:
 [[1.  2.  4. ]
 [3.  4.  3. ]
 [5.5 6.  5. ]
 [8.  8.  7. ]]


### [문제 1.2] One-Hot Encoding (2점)

결과가 동일하게 나오도록 코드의 빈칸을 채워주세요.

In [26]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# 예제 데이터 생성
data = np.array([
    ['coffee', 'morning'],
    ['tea', 'afternoon'],
    ['water', 'morning'],
    ['coffee', 'evening'],
    ['tea', 'morning'],
])

# OneHotEncoder 인스턴스 생성
encoder_drop = OneHotEncoder(drop='if_binary')

# 데이터 변환
transformed_data_drop = encoder_drop.fit_transform(data)
print(encoder_drop.get_feature_names_out())
print(transformed_data_drop.toarray())

['x0_coffee' 'x0_tea' 'x0_water' 'x1_afternoon' 'x1_evening' 'x1_morning']
[[1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]]


### [문제 1.3]  (2점)

예시 데이터의 특성을 확인하고 빈칸을 채워주세요.

In [27]:
from sklearn.preprocessing import StandardScaler
from scipy import sparse
import numpy as np

# 예제 데이터 생성
data = sparse.csr_matrix([
    [1, 2, 0],
    [0, 0, 3],
    [4, 0, 5],
])

# StandardScaler 인스턴스 생성
scaler = StandardScaler(with_mean=False)

# 데이터 표준화
standardized_data = scaler.fit_transform(data)

print(standardized_data.toarray())

[[0.58834841 2.12132034 0.        ]
 [0.         0.         1.45999279]
 [2.35339362 0.         2.43332132]]


### [문제 1.4]  (2점)

feature_range가 (-0.5, 0.5)가 되도록 코드의 빈칸을 채워주세요.

In [28]:
from sklearn.preprocessing import MinMaxScaler

# 예제 데이터 생성
data = np.array([
    [1, -1, 2],
    [2, 0, 0],
    [0, 1, -1]
])

# MinMaxScaler 인스턴스 생성
scaler = MinMaxScaler(feature_range=(-0.5,0.5))

# 데이터 스케일링
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[ 0.         -0.5         0.5       ]
 [ 0.5         0.         -0.16666667]
 [-0.5         0.5        -0.5       ]]


### [문제 1.5]  (2점)

Iris 데이터셋 로드를 로드하고 훈련 세트와 테스트 세트로 분리해주세요.

In [29]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Iris 데이터셋 로드를 로드해주세요.
iris=load_iris()
X, y = iris.data, iris.target

# 훈련 세트와 테스트 세트로 분리해주세요.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### [문제 1.6]  (2점)

KFold 객체를 생성해주세요.

In [30]:
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# KFold 객체 생성해주세요.

kf = KFold(n_splits=5, shuffle=True, random_state=42)

# KFold를 이용한 교차 검증
for train_index, test_index in kf.split(X_train):
    X_train_fold, X_test_fold = X_train[train_index], X_train[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]

    model = RandomForestClassifier(random_state=42)
    model.fit(X_train_fold, y_train_fold)
    predictions = model.predict(X_test_fold)
    print(f'Accuracy: {accuracy_score(y_test_fold, predictions)}')


Accuracy: 0.9047619047619048
Accuracy: 0.9047619047619048
Accuracy: 0.9047619047619048
Accuracy: 0.8571428571428571
Accuracy: 0.9523809523809523


### [문제 1.7]  (2점)

StratifiedKFold 객체 생성을 해주세요.

In [31]:
from sklearn.model_selection import StratifiedKFold

# StratifiedKFold 객체 생성을 해주세요.

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# StratifiedKFold를 이용한 교차 검증
for train_index, test_index in skf.split(X_train, y_train):
    X_train_fold, X_test_fold = X_train[train_index], X_train[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]

    model = RandomForestClassifier(random_state=42)
    model.fit(X_train_fold, y_train_fold)
    predictions = model.predict(X_test_fold)
    print(f'Accuracy: {accuracy_score(y_test_fold, predictions)}')

Accuracy: 0.8571428571428571
Accuracy: 0.9047619047619048
Accuracy: 0.9047619047619048
Accuracy: 0.9523809523809523
Accuracy: 0.9523809523809523


### [문제 1.8] (2점)

cross_val_score를 이용한 교차 검증을 해주세요.

In [33]:
from sklearn.model_selection import cross_val_score

# cross_val_score를 이용한 교차 검증을 해주세요.
# 폴드 수는 5로 설정해주세요.

model = RandomForestClassifier(random_state=42)
scores = cross_val_score(model, X_train, y_train, cv=5)
print(f'Cross-validation scores: {scores}')

Cross-validation scores: [0.95238095 0.9047619  0.9047619  1.         0.95238095]


### [문제 1.9] (4점)

RandomizedSearchCV 객체를 생성하고, 가장 좋은 parameter와 score을 찾아주세요.

In [34]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

# 하이퍼파라미터 설정
param_distributions = {
    'n_estimators': randint(100, 500),
    'max_depth': randint(1, 10)
}

# RandomizedSearchCV 객체 생성해주세요.
# 폴드 수는 5로 설정해주세요.
# 파라미터 검색 횟수는 20으로 설정해주세요.

random_search = RandomizedSearchCV(model, param_distributions, cv=5, n_iter=20, random_state=42)

# 훈련 데이터에 대해 하이퍼파라미터 최적화 수행
random_search.fit(X_train, y_train)

# 결과 출력(파라미터, 결과)를 해주세요.

print(f'Best parameters: {random_search.best_params_}')
print(f'Best cross-validation score: {random_search.best_score_}')

Best parameters: {'max_depth': 7, 'n_estimators': 448}
Best cross-validation score: 0.9428571428571428


# 4. Sciket-learn을 활용한 타이타닉 생존자 예측 실습 (30점)

사이킷런의 주요 모듈 및 메서드 실습이 목적이므로 상세한 EDA과정은 생략하고 최소한의 전처리만 진행합니다.

In [35]:
# data analysis and wrangling
import numpy as np
import pandas as pd

# load dataset
import seaborn as sns

In [36]:
df = sns.load_dataset("titanic")
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

- survived : 생존여부(0 : 사망, 1 : 생존)
- pclass : 객실의 등급(1, 2, 3)
- sex : 성별(male, female)
- age : 나이
- sibsp : 함께 탑승한 형제자매, 아내, 남편의 수
- parch : 함께 탑승한 부모, 자식의 수
- fare : 티켓의 요금
- embarked : 배에 탑승한 도시(C = Cherbourg, Q = Queenstown, S = Southampton
- class : 객실의 등급(First, Second, Third)
- who : 성별(man, woman)
- adult_male : 성인 남성 여부(True, False)
- embark_town : 배에 탑승한 도시(Cherbourg, Queenstown, Southampton)
- alive : 생존여부(yes, no)
- alone : 홀로 탑승 여부(True, False)

In [37]:
# class, who, adult_male, embark_town, alive, alone 변수는 타 변수들과 의미하는 바가 동일하므로 삭제합니다.
df.drop(columns = ['sibsp', 'parch', 'class', 'who', 'adult_male', 'embark_town', 'alive'], inplace = True)
df.head()

survived  pclass     sex   age     fare embarked deck  alone
0         0       3    male  22.0   7.2500        S  NaN  False
1         1       1  female  38.0  71.2833        C    C  False
2         1       3  female  26.0   7.9250        S  NaN   True
3         1       1  female  35.0  53.1000        S    C  False
4         0       3    male  35.0   8.0500        S  NaN   True

### [문제 2.1] Fill Missing Values (4점)

데이터셋의 결측치를 확인하고 삭제 혹은 적절한 값으로 대체합니다.

In [38]:
# 결측치를 확인합니다.
df.isnull().sum()
df.dropna()

survived  pclass     sex   age     fare embarked deck  alone
1           1       1  female  38.0  71.2833        C    C  False
3           1       1  female  35.0  53.1000        S    C  False
6           0       1    male  54.0  51.8625        S    E   True
10          1       3  female   4.0  16.7000        S    G  False
11          1       1  female  58.0  26.5500        S    C   True
..        ...     ...     ...   ...      ...      ...  ...    ...
871         1       1  female  47.0  52.5542        S    D  False
872         0       1    male  33.0   5.0000        S    B   True
879         1       1  female  56.0  83.1583        C    C  False
887         1       1  female  19.0  30.0000        S    B   True
889         1       1    male  26.0  30.0000        C    C   True

[182 rows x 8 columns]

In [41]:
# deck 변수는 대부분이 결측치이므로 삭제합니다.
df.drop(columns = 'deck', inplace = True)

from sklearn.impute import SimpleImputer

# age 변수의 결측치는 나이의 평균값으로 대체합니다.
imputer = SimpleImputer(strategy = 'mean')
age_column = df["age"].values.reshape(-1, 1)
df["age"] = imputer.fit_transform(age_column)

# embarked 변수의 결측치는 탑승지의 최빈값으로 대체합니다.
imputer = SimpleImputer(strategy = 'most_frequent')
embarked_column = df["embarked"].values.reshape(-1, 1)
df["embarked"] = imputer.fit_transform(embarked_column)

df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
fare        0
embarked    0
alone       0
dtype: int64

### [문제 2.2] Label Encoding (4점)

속성값이 2개인 Categorical 변수에 관하여 모델이 학습하기 용이하도록 Label Encoding을 수행합니다.

In [42]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoder 객체를 생성합니다.
le = LabelEncoder()

# sex와 alone 열을 각 속성값을 기준으로 Label Encoding 합니다.
for feature in ["sex", "alone"] :
    df[feature] = le.fit_transform(df[feature])

df.head()

survived  pclass  sex   age     fare embarked  alone
0         0       3    1  22.0   7.2500        S      0
1         1       1    0  38.0  71.2833        C      0
2         1       3    0  26.0   7.9250        S      1
3         1       1    0  35.0  53.1000        S      0
4         0       3    1  35.0   8.0500        S      1

### [문제 2.3] One-Hot Encoding (4점)

속성값이 3개 이상인 Categorical 변수에 관하여 모델이 학습하기 용이하도록 One-Hot Encoding을 수행합니다.

In [43]:
from sklearn.preprocessing import OneHotEncoder

# OneHotEncoder 객체를 생성합니다.
encoder = OneHotEncoder(sparse_output=False)

# pclass와 embarked 열을 각 속성값을 기준으로 One-Hot Encoding 합니다.
encoded_data = encoder.fit_transform(df[["pclass",'embarked']])
encoded_data

array([[0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       ...,
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.]])

scikit learn의 OneHotEncoder를 이용하면 array 형식으로 반환되기 때문에 output을 다시 원 데이터프레임과 합쳐줘야 하는 번거로움이 있습니다. 따라서, One-hot-encoding 하려는 변수가 명목 변수(categorical variable)인 경우 pandas의 get_dummies() 함수를 사용하는 것이 편리합니다.

In [44]:
# pandas의 get_dummies() 메서드를 이용해 pclass와 embarked열 One-Hot Encoding
df = pd.get_dummies(df,columns=["pclass","embarked"])
df.iloc[:, 5:] = df.iloc[:, 5:].astype('int')

df.head()

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_22816\2719403800.py:3: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.iloc[:, 5:] = df.iloc[:, 5:].astype('int')


survived  sex   age     fare  alone  pclass_1  pclass_2  pclass_3  \
0         0    1  22.0   7.2500      0         0         0         1   
1         1    0  38.0  71.2833      0         1         0         0   
2         1    0  26.0   7.9250      1         0         0         1   
3         1    0  35.0  53.1000      0         1         0         0   
4         0    1  35.0   8.0500      1         0         0         1   

   embarked_C  embarked_Q  embarked_S  
0           0           0           1  
1           1           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1

### [문제 2.4] Standardization (4점)

서로 다른 scale을 가지는 수치형 변수에 관하여 Standardization을 진행합니다.

In [45]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체를 생성합니다.
scaler = StandardScaler()

# age와 fare 열을 표준화합니다.
for feature in ["age", "fare"] :
    df[feature] = scaler.fit_transform(df[[feature]])

df.head()

survived  sex       age      fare  alone  pclass_1  pclass_2  pclass_3  \
0         0    1 -0.592481 -0.502445      0         0         0         1   
1         1    0  0.638789  0.786845      0         1         0         0   
2         1    0 -0.284663 -0.488854      1         0         0         1   
3         1    0  0.407926  0.420730      0         1         0         0   
4         0    1  0.407926 -0.486337      1         0         0         1   

   embarked_C  embarked_Q  embarked_S  
0           0           0           1  
1           1           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1

### [문제 2.5] Train-Test Split (5점)

모델이 학습할 train data와 예측을 수행할 test data를 분리합니다.

In [46]:
from sklearn.model_selection import train_test_split

# Target column은 survived입니다.
X = df.drop("survived", axis = 1)
y = df["survived"]

# train data size가 test data size의 4배가 되도록 설정하고 random state는 42로 고정합니다.
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(712, 10) (179, 10) (712,) (179,)


### [문제 2.6] Modeling (4점)

다양한 ML 분류 모델을 사용할 수 있지만 본 예제에서는 다수의 결정 트리로 구성된 앙상블 모델인 Random Forest 모델을 사용합니다.

In [48]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

# RandomForestClassifier 모델 객체를 생성합니다.
model = RandomForestClassifier()

# Train data를 모델에 학습시킵니다. 모델은 array 형식을 입력으로 받으므로 .values 메서드를 통해 데이터프레임을 array로 변환하여 학습합니다.
model.fit(X_train.values, y_train.values)

# Test data로 예측을 수행합니다.
prediction = model.predict(X_test.values)

print(pd.DataFrame(prediction, columns = ['survived']))
print(f'총 {y_test.shape[0]}명 중 {round(100 * metrics.accuracy_score(prediction, y_test), 2)}% 정확도로 생존을 예측함')

     survived
0           0
1           0
2           0
3           1
4           0
..        ...
174         0
175         0
176         0
177         1
178         1

[179 rows x 1 columns]
총 179명 중 79.89% 정확도로 생존을 예측함


### [문제 2.7] GridSearch (5점)

GridSearch를 이용해 모델의 최적 하이퍼파라미터를 찾고 예측 정확도가 개선되었는지 확인합니다.

In [49]:
from sklearn.model_selection import GridSearchCV

# 탐색할 하이퍼파라미터 딕셔너리를 생성합니다.
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# GridSearchCV 객체를 생성합니다. 교차 검증 fold수는 5로, 평가 지표는 accuracy로 설정합니다.
grid_search = GridSearchCV(estimator=RandomForestClassifier(),param_grid=param_grid,cv=5, scoring='accuracy')

# 모델을 훈련하고 최적 하이퍼파라미터를 탐색합니다.
grid_search.fit(X_train.values,y_train.values)

print("최적 하이퍼파라미터:", grid_search.best_params_)

# 최적 모델을 저장합니다.
best_model = grid_search.best_estimator_

# 테스트 데이터에 대한 예측 및 정확도 출력
prediction = best_model.predict(X_test.values)

print(f'총 {y_test.shape[0]}명 중 {round(100 * metrics.accuracy_score(prediction, y_test), 2)}% 정확도로 생존을 예측함')

최적 하이퍼파라미터: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 50}
총 179명 중 82.12% 정확도로 생존을 예측함
