### 1. Numpy 활용

넘파이 설치 및 import

In [1]:
# pip install numpy
!pip install numpy # For Google Colab

ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# Numpy의 경우 보통 np라는 명칭으로 임포트합니다.
import numpy as np

1.1 (3점)

numpy를 활용하여 넘파이 배열을 생성해주세요. 

In [3]:
A = np.array([1.0, 3.0, 5.0])
print(A, type(A))

[1. 3. 5.] <class 'numpy.ndarray'>


1.2 (5점)

numpy를 활용하여 다양한 종류의 넘파이 배열을 생성해주세요.

In [6]:
print(np.zeros(5))
print(np.ones(5))
print(np.arange(5))
print(np.full((2, 3), 5))
print(np.eye(3))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.3 (4점)

주어진 배열과 실행 결과를 보고, ??? 된 부분을 작성해주세요.

In [10]:
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int32


1.4 (3점)

주어진 코드를 보고, 실행 결과를 작성해주세요.

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 4], [6, 8]])

print(A+B)
print(A-B)
print(A*B)
print(A/B)

[[ 3  6]
 [ 9 12]]
[[-1 -2]
 [-3 -4]]
[[ 2  8]
 [18 32]]
[[0.5 0.5]
 [0.5 0.5]]


1.5 (5점)

주어진 배열과 실행 결과를 보고, ??? 된 부분을 작성해주세요.

In [13]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print(A*B)
print(A @ B)
print(np.matmul(A,B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


1.6 (5점)

주어진 코드를 보고, 실행 결과를 작성해주세요.

In [14]:
A = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
B = np.array(A)
B = B[0:2, 0:2]

print(B)

[[1 2]
 [4 5]]


### 2. Pandas 활용

판다스 설치 및 import

In [15]:
# pip install pandas
!pip install pandas # For Google Colab

ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [16]:
# Pandas의 경우 보통 pd라는 명칭으로 임포트합니다.
import pandas as pd

2.1 (3점)

주어진 데이터셋(titanic.csv)를 Pandas를 활용해 읽고, 출력해주세요.

In [17]:
df = pd.read_csv("./titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

2.2 (3점)

데이터셋의 Index와 Columns를 각각 출력해주세요.

In [18]:
print('Index : {0}'.format(df.index))
print('Columns : {0}'.format(df.columns))

Index : RangeIndex(start=0, stop=891, step=1)
Columns : Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


2.3 (5점)

데이터셋에서 앞부분 7명의 데이터를 출력하고 7번째 사람의 성별을 작성해주세요.

In [19]:
df.head(7)
# 7번째 사람의 성별은? : m

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S

2.4 (3점)

데이터셋의 결측치를 확인해주세요.




In [23]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

2.5 (5점)

확인한 결측치를 다음과 같이 수정해주세요.
*   Age -> 평균값
*   Cabin -> 'Unknown'으로 대체
*   Embarked -> 최빈값

In [24]:
df['Age'].mean()

df['Cabin'].fillna("Unknown", inplace=True)

Mode = df['Embarked'].mode()[0]
df['Embarked'].fillna(Mode, inplace=True)

2.6 (3점)

데이터셋의 "Name" 컬럼을 삭제해주세요.

In [27]:
df.drop(columns=['Name'],inplace=True)

2.7 (3점)

데이터셋의 "PassengerId" 컬럼명을 "ID"로 변경해주세요.

In [28]:
df = df.rename(columns={'PassengerId':'ID'}, inplace=True)

---

## 2조

비타민 13기 여러분 안녕하세요! 🍊

학기세션 2주차 예습과제를 출제한 2조입니다.

2주차 예습과제의 두 번째 파트에서는 Scikit-learn에 대해 공부합니다.

1번 문항에서는 개념 위주로, 2번 문항에서는 실습 위주로 출제될 예정이니 참고 바랍니다.

## 1번 문항

### Q1-1. 사이킷런이 무엇인지에 대해 서술하시오. (2점)

> 파이썬에서 머신러닝을 구현할 수 있는 오픈 소스 라이브러리

### Q1-2. 다음 중 사이킷런에서 제공하지 않는 모델은? (2점)

1. sklearn.preprocessing
2. sklearn.ensemble
3. sklearn.accuracy
4. sklearn.pipeline
5. sklearn.cluster

> 3

### Q1-3. 교차검증의 정의와 목적을 서술하시오. (2점)

> 머신러닝 모델의 성능을 평가할 때, 모델의 신뢰를 높이고 과적합 방지, 최적의 하이퍼파라미터를 선택하기 위해 사용

### Q1-4. k-fold 교차검증과 stratified k-fold 교차검증의 개념/용도별 차이를 구체적으로 서술하시오. (4점)

> k-fold는 단순히 데이터를 k개의 서브셋으로 나눠 평가하는데 Stratified는 각 fold에서 클래스 비율 유지해서 평가한다. 그렇기에 데이터 불균형할 때 유리하다.

### Q1-5. 아래는 사이킷런의 모듈 중 하나인 'model_selection'의 함수 중 하나인 train_test_split( )의 파라미터 일부이다. 각 파라미터에 대한 설명과 default 값을 각각 적으시오. (3점)

- test_size
- train_size
- shuffle
- random_state

> 테스트 데이터, 훈련 데이터, 무작위 셔플, 데이터 분할 시 시드값
0.25, None, True, None

### Q1-6. 표준화와 정규화에 대한 설명을 각각 설명하시오. (3점)

> 표준화는 표준 정규분포에 가까워지게 만드는 것이고, 정규화는 특정 범위 안으로 변환하는 것이다.

### Q1-7. GridSearchCV와 RandomSearchCV의 차이점을 구체적으로 서술하시오. (4점)

> 둘은 최적의 하이퍼파라미터 값을 찾는 것으로, 그리드의 경우 모든 조합을 사용해 계산 비용이 높고 랜덤은 무작위하게 조합해 최적의 조합을 못 찾을수도 있다.

---

## 2번 문항

다음은 사이킷런의 당뇨병 환자 데이터셋을 이용하여 모델을 학습시키는 코드입니다. 다음 빈칸을 채우시오.

### Q2-1. 2번 문항 전체에서 사용된 model_selection 모듈의 함수 세 가지, 사이킷런의 당뇨병 데이터셋을 import 하시오. (14점)

In [29]:
# 2번 전체 문항에서 사용된 model_selection 모듈의 함수 세 가지를 import 하시요.
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import numpy as np

# 사이킷런의 당뇨병 데이터셋을 로드하는 코드를 입력하시오.
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()

# 특성 데이터와 타겟 데이터를 가져옴
X = diabetes.data
y = diabetes.target

### Q2-2. diabetes 데이터를를 test data와 train data로 분리하시오 (단, train data와 test data의 비율은 8:2, random_state는 자신의 나이로 설정) (6점)

In [30]:
# diabetes를 test data와 train data로 분리하시오
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=25)

### Q2-3. 선형회귀 객체를 만들고 학습과 예측을 수행하시오 (10점)

In [31]:
# 선형회귀 객체 생성
linear_reg = LinearRegression()

# 학습 진행
linear_reg.fit(X_train, y_train)

# 예측
y_pred = linear_reg.predict(X_test)

# 회귀 지표인 평균 제곱 오차 및 상관계수 계산
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

### Q2-4. KFold 객체를 만들어서 kf 변수에 저장하시오 (단, K=5로 두고 진행하세요) (5점)

In [33]:
# 교차 검증을 하는 코드입니다.
# KFold 객체를 만들어서 kf 변수에 저장하시오
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# 평균 제곱 오차를 저장할 리스트 생성
mse_scores = []

# 각 폴드에 대해 학습과 예측 수행
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]  # 훈련 데이터와 검증 데이터로 분할
    y_train, y_test = y[train_index], y[test_index]

    # 선형 회귀 모델 객체 생성
    linear_reg = LinearRegression()
    linear_reg.fit(X_train, y_train)
    y_pred = linear_reg.predict(X_test)

    # 평균 제곱 오차 계산 및 저장
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# 평균 제곱 오차의 평균 계산
avg_mse = np.mean(mse_scores)

### Q2-5. 교차 검증을 진행하는 또 다른 함수를 작성하시오. (5점)

from sklearn.model_selection import cross_val_score
mse_scores = cross_val_score(linear_reg, X, y, scoring='neg_mean_squared_error', cv=5)